services:
  backend:
    image: kayasem/${COMPOSE_PROJECT_NAME}-backend:latest
    container_name: ${COMPOSE_PROJECT_NAME}_backend
    restart: always
    environment:
      DATABASE_URL: ${PROD_DATABASE_URL}
      LOG_LEVEL: ${PROD_LOG_LEVEL}
    depends_on:
      database:
        condition: service_healthy
    networks:
      - app_network
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.main-api.rule=PathPrefix(`/api`)"
      - "traefik.http.middlewares.api-strip.stripprefix.prefixes=/api"
      - "traefik.http.routers.main-api.middlewares=api-strip"
      - "traefik.http.routers.main-api.entrypoints=websecure"
      - "traefik.http.services.main-api.loadbalancer.server.port=3001"
      - "traefik.http.routers.main-api.priority=10"
      - "traefik.http.routers.main-api.tls.certresolver=letsencrypt"

  frontend:
    image: kayasem/${COMPOSE_PROJECT_NAME}-frontend:latest
    container_name: ${COMPOSE_PROJECT_NAME}_frontend
    restart: always
    networks:
      - app_network
      - traefik
    environment:
      - NEXT_PUBLIC_SITE_URL=${NEXT_PUBLIC_SITE_URL}
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_SITE_URL}/api
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.main.rule=PathPrefix(`/`)"
      - "traefik.http.routers.main.entrypoints=websecure"
      - "traefik.http.services.main.loadbalancer.server.port=3000"
      - "traefik.http.routers.main.priority=1"
      - "traefik.http.routers.main.tls.certresolver=letsencrypt"

  database:
    image: postgres:16
    container_name: ${COMPOSE_PROJECT_NAME}_database
    restart: always
    environment:
      POSTGRES_USER: ${PROD_DB_USER}
      POSTGRES_PASSWORD: ${PROD_DB_PASSWORD}
      POSTGRES_DB: ${PROD_DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${PROD_DB_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:

networks:
  app_network:
    driver: bridge
  traefik:
    external: true
