name: "Generate Production Env"
description: "Creates a .env file for production using inputs (including secrets)"

inputs:
  project_name:
    description: "Project name"
    required: true
  db_user:
    description: "Database user"
    required: true
  db_password:
    description: "Database password"
    required: true
  db_name:
    description: "Database name"
    required: true

runs:
  using: "composite"
  steps:
    - name: Create production .env
      shell: bash
      run: |
        COMPOSE_PROJECT_NAME=${{ inputs.project_name }}
        PROD_DB_USER=${{ inputs.db_user }}
        PROD_DB_PASSWORD=${{ inputs.db_password }}
        PROD_DB_NAME=${{ inputs.db_name }}
        PREVIEW_SITE_URL=${{ inputs.public_site_url }}

        PROD_DATABASE_URL="postgres://${PROD_DB_USER}:${PROD_DB_PASSWORD}@${COMPOSE_PROJECT_NAME}_database:5432/${PROD_DB_NAME}"

        cat > .env <<EOF
        COMPOSE_PROJECT_NAME=$COMPOSE_PROJECT_NAME
        PROD_DB_USER=$PROD_DB_USER
        PROD_DB_PASSWORD=$PROD_DB_PASSWORD
        PROD_DB_NAME=$PROD_DB_NAME
        PROD_DATABASE_URL=$PROD_DATABASE_URL
        NEXT_PUBLIC_SITE_URL=$PREVIEW_SITE_URL
        EOF

        echo "Production .env generated."
