name: "Generate Production Env"
description: "Creates a .env file for production using inputs (including secrets)"

inputs:
  project_name:
    description: "Project name"
    required: true
  prod_host:
    description: "Host domain"
    required: true
  db_user:
    description: "Database user"
    required: true
  db_password:
    description: "Database password"
    required: true
  db_name:
    description: "Database name"
    required: true
  public_site_url:
    description: "Public site url"
    required: true
  api_key_404:
    description: "API key for the viernulvier API"
    required: true

runs:
  using: "composite"
  steps:
    - name: Create production .env
      shell: bash
      run: |
        COMPOSE_PROJECT_NAME=${{ inputs.project_name }}
        PROD_HOST=${{ inputs.prod_host }}
        PROD_DB_USER=${{ inputs.db_user }}
        PROD_DB_PASSWORD=${{ inputs.db_password }}
        PROD_DB_NAME=${{ inputs.db_name }}
        PROD_SITE_URL=${{ inputs.public_site_url }}

        PROD_DATABASE_URL="postgres://${PROD_DB_USER}:${PROD_DB_PASSWORD}@${COMPOSE_PROJECT_NAME}_database:5432/${PROD_DB_NAME}"
        PROD_API_KEY_404=${{ inputs.api_key_404 }}
        cat > .env <<EOF
        COMPOSE_PROJECT_NAME=$COMPOSE_PROJECT_NAME
        PROD_HOST=$PROD_HOST
        PROD_DB_USER=$PROD_DB_USER
        PROD_DB_PASSWORD=$PROD_DB_PASSWORD
        PROD_DB_NAME=$PROD_DB_NAME
        PROD_DATABASE_URL=$PROD_DATABASE_URL
        NEXT_PUBLIC_SITE_URL=$PROD_SITE_URL
        PROD_API_KEY_404=$PROD_API_KEY_404
        EOF

        echo "Production .env generated."
