/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Login to the API */
        post: operations["auth_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Logout and invalidate sessions */
        post: operations["logout_and_invalidate_sessions"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Refresh the access token using the refresh cookie */
        post: operations["refresh_access_token"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/collections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Return all collections with their items. Public endpoint, no authentication required. Each collection contains the full list of its items in position order. */
        get: operations["get_all_collections"];
        /** @description Update the metadata (slug, titles, descriptions) of an existing collection. Requires editor authentication. Does not affect items — use the items sub-resource for that. */
        put: operations["update_collection"];
        /** @description Create a new collection. Requires editor authentication. Supply a human-readable slug that will appear in the shareable URL (e.g. `videodroom-candidates-2026`) and per-language translations (title required, description required but may be empty). Items are added separately via POST /collections/{id}/items. */
        post: operations["create_collection"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/collections/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Return a single collection by its UUID, including all its items in position order. Public endpoint, no authentication required. Use this to render the shareable collection page for a recipient. */
        get: operations["get_one_collection"];
        put?: never;
        post?: never;
        /** @description Permanently delete a collection and all its items (cascade). Requires editor authentication. This action is irreversible and invalidates any shared URLs pointing to this collection. */
        delete: operations["delete_collection"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/collections/{id}/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Add an item to a collection. Requires editor authentication. An item links a content_id (UUID of the referenced entity) and a content_type (Production, Event, Blogpost, Artist, or Location) with an optional bilingual curator comment and an explicit position for ordering. */
        post: operations["add_collection_item"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/collections/{id}/items/{item_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** @description Remove a single item from a collection. Requires editor authentication. Does not affect the other items or the collection itself. */
        delete: operations["delete_collection_item"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/editor/create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Create a new editor user (Admin only) */
        post: operations["create_editor"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/editor/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Receive editor info of the logged in user */
        get: operations["get_editor_info"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get all events */
        get: operations["get_all_events"];
        /** @description Update an event */
        put: operations["update_event"];
        /** @description Create an event */
        post: operations["create_event"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get an event by id */
        get: operations["get_event_by_id"];
        put?: never;
        post?: never;
        /** @description Delete an event */
        delete: operations["delete_event"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/halls": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get all halls */
        get: operations["get_all_halls"];
        /** @description Update the fields of a hall */
        put: operations["update_hall"];
        /** @description Create a hall */
        post: operations["create_hall"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/halls/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get a hall by id */
        get: operations["get_one_hall"];
        put?: never;
        post?: never;
        /** @description Delete a hall */
        delete: operations["delete_hall"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/locations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get all locations */
        get: operations["get_all_locations"];
        /** @description Update the fields of a location */
        put: operations["update_location"];
        /** @description Create a location */
        post: operations["create_location"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/locations/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get location by id */
        get: operations["get_one_location"];
        put?: never;
        post?: never;
        /** @description Delete a location */
        delete: operations["delete_location"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/productions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get all productions */
        get: operations["get_all_productions"];
        /** @description Update the fields of a production */
        put: operations["update_production"];
        /** @description Create a production */
        post: operations["create_production"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/productions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get a production by id */
        get: operations["get_one_production"];
        put?: never;
        post?: never;
        /** @description Delete a production */
        delete: operations["delete_production"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/productions/{id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get all events for a production */
        get: operations["get_events_by_production_id"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/spaces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get all spaces */
        get: operations["get_all_spaces"];
        /** @description Update the fields of a space */
        put: operations["update_space"];
        /** @description Create a space */
        post: operations["create_space"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/spaces/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get a space by id */
        get: operations["get_one_space"];
        put?: never;
        post?: never;
        /** @description Delete a space */
        delete: operations["delete_space"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/taxonomy/facets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get all facets with their tags */
        get: operations["get_facets"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get server build version */
        get: operations["get_build_version"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AuthResponse: {
            message: string;
            success: boolean;
        };
        /** @enum {string} */
        CollectionContentType: "production" | "event" | "blogpost" | "artist" | "location";
        CollectionItemPayload: {
            /**
             * Format: uuid
             * @description UUID of the referenced archive entity (production, event, artist, …).
             */
            content_id: string;
            /** @description Type of the referenced entity. */
            content_type: components["schemas"]["CollectionContentType"];
            /**
             * Format: date-time
             * @description ISO 8601 timestamp when the item was added to the collection.
             */
            created_at: string;
            /**
             * Format: uuid
             * @description Unique identifier for this collection item.
             */
            id: string;
            /**
             * Format: int32
             * @description Display order within the collection (1-based).
             */
            position: number;
            /** @description Per-language curator annotation for this item. */
            translations: components["schemas"]["CollectionItemTranslationPayload"][];
        };
        CollectionItemPostPayload: {
            /**
             * Format: uuid
             * @description UUID of the referenced archive entity (production, event, artist, …).
             */
            content_id: string;
            /** @description Type of the referenced entity. */
            content_type: components["schemas"]["CollectionContentType"];
            /**
             * Format: int32
             * @description Display order within the collection (1-based).
             */
            position: number;
            /** @description Per-language curator annotation for this item. */
            translations?: components["schemas"]["CollectionItemTranslationPayload"][];
        };
        CollectionItemTranslationPayload: {
            comment?: string | null;
            language_code: string;
        };
        CollectionPayload: {
            /**
             * Format: date-time
             * @description ISO 8601 creation timestamp.
             */
            created_at: string;
            /**
             * Format: uuid
             * @description Unique identifier for the collection (UUIDv7).
             */
            id: string;
            /** @description Ordered list of items in this collection. */
            items: components["schemas"]["CollectionItemPayload"][];
            /** @description URL-safe identifier used in the shareable link, e.g. `videodroom-candidates-2026`. Must be unique across all collections. */
            slug: string;
            /** @description Per-language title and description. */
            translations: components["schemas"]["CollectionTranslationPayload"][];
            /**
             * Format: date-time
             * @description ISO 8601 last-updated timestamp.
             */
            updated_at: string;
        };
        CollectionPostPayload: {
            /** @description URL-safe identifier used in the shareable link, e.g. `videodroom-candidates-2026`. Must be unique across all collections. */
            slug: string;
            /** @description Per-language title and description. */
            translations: components["schemas"]["CollectionTranslationPayload"][];
        };
        CollectionTranslationPayload: {
            description: string;
            language_code: string;
            title: string;
        };
        CreateEditorRequest: {
            email: string;
            password: string;
            username: string;
        };
        EditorResponse: {
            email: string;
            id: string;
            role: components["schemas"]["UserRole"];
        };
        /** @enum {string} */
        EntityType: "production" | "artist" | "article" | "media";
        ErrorResponse: {
            /** @example An error occurred during processing */
            message: string;
            success: boolean;
        };
        EventPayload: {
            box_office_id?: string | null;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            doors_at?: string | null;
            /** Format: date-time */
            ends_at?: string | null;
            /** Format: uuid */
            hall_id?: string | null;
            /** Format: uuid */
            id: string;
            /** Format: date-time */
            intermission_at?: string | null;
            /** Format: int32 */
            max_tickets_per_order?: number | null;
            /** Format: uuid */
            production_id: string;
            /** Format: int32 */
            source_id?: number | null;
            /** Format: date-time */
            starts_at: string;
            status: string;
            uitdatabank_id?: string | null;
            /** Format: date-time */
            updated_at: string;
            vendor_id?: string | null;
        };
        EventPostPayload: {
            box_office_id?: string | null;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            doors_at?: string | null;
            /** Format: date-time */
            ends_at?: string | null;
            /** Format: uuid */
            hall_id?: string | null;
            /** Format: date-time */
            intermission_at?: string | null;
            /** Format: int32 */
            max_tickets_per_order?: number | null;
            /** Format: uuid */
            production_id: string;
            /** Format: int32 */
            source_id?: number | null;
            /** Format: date-time */
            starts_at: string;
            status: string;
            uitdatabank_id?: string | null;
            /** Format: date-time */
            updated_at: string;
            vendor_id?: string | null;
        };
        /** @enum {string} */
        Facet: "discipline" | "format" | "theme" | "audience";
        FacetResponse: {
            slug: string;
            tags: components["schemas"]["TagResponse"][];
            translations: components["schemas"]["FacetTranslationPayload"][];
        };
        FacetTranslationPayload: {
            label: string;
            language_code: string;
        };
        HallPayload: {
            box_office_id?: string | null;
            /** Format: uuid */
            id: string;
            name: string;
            open_seating?: boolean | null;
            remark?: string | null;
            seat_selection?: boolean | null;
            slug: string;
            /** Format: int32 */
            source_id?: number | null;
            /** Format: uuid */
            space_id?: string | null;
            vendor_id?: string | null;
        };
        HallPostPayload: {
            box_office_id?: string | null;
            name: string;
            open_seating?: boolean | null;
            remark?: string | null;
            seat_selection?: boolean | null;
            slug: string;
            /** Format: int32 */
            source_id?: number | null;
            /** Format: uuid */
            space_id?: string | null;
            vendor_id?: string | null;
        };
        LocationPayload: {
            city?: string | null;
            code?: string | null;
            country?: string | null;
            /** Format: uuid */
            id: string;
            is_owned_by_viernulvier?: boolean | null;
            name?: string | null;
            number?: string | null;
            phone_1?: string | null;
            phone_2?: string | null;
            postal_code?: string | null;
            slug?: string | null;
            /** Format: int32 */
            source_id?: number | null;
            street?: string | null;
            uitdatabank_id?: string | null;
        };
        LocationPostPayload: {
            city?: string | null;
            code?: string | null;
            country?: string | null;
            is_owned_by_viernulvier?: boolean | null;
            name?: string | null;
            number?: string | null;
            phone_1?: string | null;
            phone_2?: string | null;
            postal_code?: string | null;
            slug?: string | null;
            /** Format: int32 */
            source_id?: number | null;
            street?: string | null;
            uitdatabank_id?: string | null;
        };
        LoginRequest: {
            email: string;
            password: string;
        };
        PaginatedResponse_EventPayload: {
            data: {
                box_office_id?: string | null;
                /** Format: date-time */
                created_at: string;
                /** Format: date-time */
                doors_at?: string | null;
                /** Format: date-time */
                ends_at?: string | null;
                /** Format: uuid */
                hall_id?: string | null;
                /** Format: uuid */
                id: string;
                /** Format: date-time */
                intermission_at?: string | null;
                /** Format: int32 */
                max_tickets_per_order?: number | null;
                /** Format: uuid */
                production_id: string;
                /** Format: int32 */
                source_id?: number | null;
                /** Format: date-time */
                starts_at: string;
                status: string;
                uitdatabank_id?: string | null;
                /** Format: date-time */
                updated_at: string;
                vendor_id?: string | null;
            }[];
            next_cursor?: string | null;
        };
        PaginatedResponse_HallPayload: {
            data: {
                box_office_id?: string | null;
                /** Format: uuid */
                id: string;
                name: string;
                open_seating?: boolean | null;
                remark?: string | null;
                seat_selection?: boolean | null;
                slug: string;
                /** Format: int32 */
                source_id?: number | null;
                /** Format: uuid */
                space_id?: string | null;
                vendor_id?: string | null;
            }[];
            next_cursor?: string | null;
        };
        PaginatedResponse_LocationPayload: {
            data: {
                city?: string | null;
                code?: string | null;
                country?: string | null;
                /** Format: uuid */
                id: string;
                is_owned_by_viernulvier?: boolean | null;
                name?: string | null;
                number?: string | null;
                phone_1?: string | null;
                phone_2?: string | null;
                postal_code?: string | null;
                slug?: string | null;
                /** Format: int32 */
                source_id?: number | null;
                street?: string | null;
                uitdatabank_id?: string | null;
            }[];
            next_cursor?: string | null;
        };
        PaginatedResponse_ProductionPayload: {
            data: {
                eticket_info?: string | null;
                /** Format: uuid */
                id: string;
                slug: string;
                /** Format: int32 */
                source_id?: number | null;
                translations: components["schemas"]["ProductionTranslationPayload"][];
                uitdatabank_theme?: string | null;
                uitdatabank_type?: string | null;
                video_1?: string | null;
                video_2?: string | null;
            }[];
            next_cursor?: string | null;
        };
        PaginatedResponse_SpacePayload: {
            data: {
                /** Format: uuid */
                id: string;
                /** Format: uuid */
                location_id: string;
                name_nl: string;
                /** Format: int32 */
                source_id?: number | null;
            }[];
            next_cursor?: string | null;
        };
        ProductionPayload: {
            eticket_info?: string | null;
            /** Format: uuid */
            id: string;
            slug: string;
            /** Format: int32 */
            source_id?: number | null;
            translations: components["schemas"]["ProductionTranslationPayload"][];
            uitdatabank_theme?: string | null;
            uitdatabank_type?: string | null;
            video_1?: string | null;
            video_2?: string | null;
        };
        ProductionPostPayload: {
            eticket_info?: string | null;
            slug: string;
            /** Format: int32 */
            source_id?: number | null;
            translations: components["schemas"]["ProductionTranslationPayload"][];
            uitdatabank_theme?: string | null;
            uitdatabank_type?: string | null;
            video_1?: string | null;
            video_2?: string | null;
        };
        /** @description The per-language content for a production. */
        ProductionTranslationPayload: {
            artist?: string | null;
            description?: string | null;
            description_2?: string | null;
            description_extra?: string | null;
            description_short?: string | null;
            info?: string | null;
            language_code: string;
            meta_description?: string | null;
            meta_title?: string | null;
            programme?: string | null;
            quote?: string | null;
            quote_source?: string | null;
            supertitle?: string | null;
            tagline?: string | null;
            teaser?: string | null;
            title?: string | null;
        };
        SpacePayload: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            location_id: string;
            name_nl: string;
            /** Format: int32 */
            source_id?: number | null;
        };
        SpacePostPayload: {
            /** Format: uuid */
            location_id: string;
            name_nl: string;
            /** Format: int32 */
            source_id?: number | null;
        };
        TagResponse: {
            slug: string;
            /** Format: int32 */
            sort_order: number;
            translations: components["schemas"]["TagTranslationPayload"][];
        };
        TagTranslationPayload: {
            description?: string | null;
            label: string;
            language_code: string;
        };
        /** @enum {string} */
        UserRole: "admin" | "editor" | "user";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    auth_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    logout_and_invalidate_sessions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Logged out successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
        };
    };
    refresh_access_token: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            /** @description Unauthorized - Invalid or expired refresh token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_all_collections: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CollectionPayload"][];
                };
            };
        };
    };
    update_collection: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CollectionPayload"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CollectionPayload"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    create_collection: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CollectionPostPayload"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CollectionPayload"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_one_collection: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Collection UUID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CollectionPayload"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    delete_collection: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Collection UUID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    add_collection_item: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Collection UUID */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CollectionItemPostPayload"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CollectionItemPayload"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    delete_collection_item: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Collection UUID */
                id: string;
                /** @description Collection item UUID */
                item_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    create_editor: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateEditorRequest"];
            };
        };
        responses: {
            /** @description Editor created successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EditorResponse"];
                };
            };
            /** @description Unauthorized - Not an admin */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_editor_info: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EditorResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_all_events: {
        parameters: {
            query?: {
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedResponse_EventPayload"];
                };
            };
        };
    };
    update_event: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EventPayload"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventPayload"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    create_event: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EventPostPayload"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventPayload"];
                };
            };
        };
    };
    get_event_by_id: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Event UUID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventPayload"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    delete_event: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Event UUID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_all_halls: {
        parameters: {
            query?: {
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedResponse_HallPayload"];
                };
            };
        };
    };
    update_hall: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HallPayload"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HallPayload"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    create_hall: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HallPostPayload"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HallPayload"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_one_hall: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Hall UUID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HallPayload"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    delete_hall: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Hall UUID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_all_locations: {
        parameters: {
            query?: {
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedResponse_LocationPayload"];
                };
            };
        };
    };
    update_location: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LocationPayload"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LocationPayload"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    create_location: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LocationPostPayload"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LocationPayload"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_one_location: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Location UUID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LocationPayload"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    delete_location: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Location UUID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_all_productions: {
        parameters: {
            query?: {
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedResponse_ProductionPayload"];
                };
            };
        };
    };
    update_production: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProductionPayload"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductionPayload"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    create_production: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProductionPostPayload"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductionPayload"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_one_production: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Production UUID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductionPayload"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    delete_production: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Production UUID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_events_by_production_id: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Production UUID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventPayload"][];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_all_spaces: {
        parameters: {
            query?: {
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedResponse_SpacePayload"];
                };
            };
        };
    };
    update_space: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SpacePayload"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpacePayload"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    create_space: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SpacePostPayload"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpacePayload"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_one_space: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Space UUID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpacePayload"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    delete_space: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Space UUID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_facets: {
        parameters: {
            query?: {
                /** @description Filter facets by entity type */
                entity_type?: null | components["schemas"]["EntityType"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FacetResponse"][];
                };
            };
        };
    };
    get_build_version: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
        };
    };
}
