/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Login to the API */
        post: operations["auth_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Logout and invalidate sessions */
        post: operations["logout_and_invalidate_sessions"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Refresh the access token using the refresh cookie */
        post: operations["refresh_access_token"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/editor/create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Create a new editor user (Admin only) */
        post: operations["create_editor"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/editor/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Receive editor info of the logged in user */
        get: operations["get_editor_info"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/halls": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get all halls */
        get: operations["get_all_halls"];
        /** @description Update the fields of a hall */
        put: operations["update_hall"];
        /** @description Create a hall */
        post: operations["create_hall"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/halls/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get a hall by id */
        get: operations["get_one_hall"];
        put?: never;
        post?: never;
        /** @description Delete a hall */
        delete: operations["delete_hall"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/locations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get all locations */
        get: operations["get_all_locations"];
        /** @description Update the fields of a location */
        put: operations["update_location"];
        /** @description Create a location */
        post: operations["create_location"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/locations/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get location by id */
        get: operations["get_one_location"];
        put?: never;
        post?: never;
        /** @description Delete a location */
        delete: operations["delete_location"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/productions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get all productions */
        get: operations["get_all_productions"];
        /** @description Update the fields of a production */
        put: operations["update_production"];
        /** @description Create a production */
        post: operations["create_production"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/productions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get a production by id */
        get: operations["get_one_production"];
        put?: never;
        post?: never;
        /** @description Delete a production */
        delete: operations["delete_production"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/spaces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get all spaces */
        get: operations["get_all_spaces"];
        /** @description Update the fields of a space */
        put: operations["update_space"];
        /** @description Create a space */
        post: operations["create_space"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/spaces/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get a space by id */
        get: operations["get_one_space"];
        put?: never;
        post?: never;
        /** @description Delete a space */
        delete: operations["delete_space"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get server build version */
        get: operations["get_build_version"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AuthResponse: {
            message: string;
            success: boolean;
        };
        CreateEditorRequest: {
            email: string;
            password: string;
            username: string;
        };
        EditorResponse: {
            email: string;
            id: string;
            role: components["schemas"]["UserRole"];
        };
        ErrorResponse: {
            /** @example An error occurred during processing */
            message: string;
            success: boolean;
        };
        HallPayload: {
            box_office_id?: string | null;
            /** Format: uuid */
            id: string;
            name: string;
            open_seating?: boolean | null;
            remark?: string | null;
            seat_selection?: boolean | null;
            slug: string;
            /** Format: int32 */
            source_id?: number | null;
            /** Format: uuid */
            space_id?: string | null;
            vendor_id?: string | null;
        };
        HallPostPayload: {
            box_office_id?: string | null;
            name: string;
            open_seating?: boolean | null;
            remark?: string | null;
            seat_selection?: boolean | null;
            slug: string;
            /** Format: int32 */
            source_id?: number | null;
            /** Format: uuid */
            space_id?: string | null;
            vendor_id?: string | null;
        };
        LocationPayload: {
            city?: string | null;
            code?: string | null;
            country?: string | null;
            /** Format: uuid */
            id: string;
            is_owned_by_viernulvier?: boolean | null;
            name?: string | null;
            number?: string | null;
            phone_1?: string | null;
            phone_2?: string | null;
            postal_code?: string | null;
            /** Format: int32 */
            source_id?: number | null;
            street?: string | null;
            uitdatabank_id?: string | null;
        };
        LocationPostPayload: {
            city?: string | null;
            code?: string | null;
            country?: string | null;
            is_owned_by_viernulvier?: boolean | null;
            name?: string | null;
            number?: string | null;
            phone_1?: string | null;
            phone_2?: string | null;
            postal_code?: string | null;
            /** Format: int32 */
            source_id?: number | null;
            street?: string | null;
            uitdatabank_id?: string | null;
        };
        LoginRequest: {
            email: string;
            password: string;
        };
        ProductionPayload: {
            artist_en?: string | null;
            artist_nl?: string | null;
            description_2_en?: string | null;
            description_2_nl?: string | null;
            description_en?: string | null;
            description_extra_en?: string | null;
            description_extra_nl?: string | null;
            description_nl?: string | null;
            description_short_en?: string | null;
            description_short_nl?: string | null;
            eticket_info?: string | null;
            /** Format: uuid */
            id: string;
            info_en?: string | null;
            info_nl?: string | null;
            meta_description_en?: string | null;
            meta_description_nl?: string | null;
            meta_title_en?: string | null;
            meta_title_nl?: string | null;
            programme_en?: string | null;
            programme_nl?: string | null;
            quote_en?: string | null;
            quote_nl?: string | null;
            quote_source_en?: string | null;
            quote_source_nl?: string | null;
            slug: string;
            /** Format: int32 */
            source_id?: number | null;
            supertitle_en?: string | null;
            supertitle_nl?: string | null;
            tagline_en?: string | null;
            tagline_nl?: string | null;
            teaser_en?: string | null;
            teaser_nl?: string | null;
            title_en?: string | null;
            title_nl?: string | null;
            uitdatabank_theme?: string | null;
            uitdatabank_type?: string | null;
            video_1?: string | null;
            video_2?: string | null;
        };
        ProductionPostPayload: {
            artist_en?: string | null;
            artist_nl?: string | null;
            description_2_en?: string | null;
            description_2_nl?: string | null;
            description_en?: string | null;
            description_extra_en?: string | null;
            description_extra_nl?: string | null;
            description_nl?: string | null;
            description_short_en?: string | null;
            description_short_nl?: string | null;
            eticket_info?: string | null;
            info_en?: string | null;
            info_nl?: string | null;
            meta_description_en?: string | null;
            meta_description_nl?: string | null;
            meta_title_en?: string | null;
            meta_title_nl?: string | null;
            programme_en?: string | null;
            programme_nl?: string | null;
            quote_en?: string | null;
            quote_nl?: string | null;
            quote_source_en?: string | null;
            quote_source_nl?: string | null;
            slug: string;
            /** Format: int32 */
            source_id?: number | null;
            supertitle_en?: string | null;
            supertitle_nl?: string | null;
            tagline_en?: string | null;
            tagline_nl?: string | null;
            teaser_en?: string | null;
            teaser_nl?: string | null;
            title_en?: string | null;
            title_nl?: string | null;
            uitdatabank_theme?: string | null;
            uitdatabank_type?: string | null;
            video_1?: string | null;
            video_2?: string | null;
        };
        SpacePayload: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            location_id: string;
            name_nl: string;
            /** Format: int32 */
            source_id?: number | null;
        };
        SpacePostPayload: {
            /** Format: uuid */
            location_id: string;
            name_nl: string;
            /** Format: int32 */
            source_id?: number | null;
        };
        /** @enum {string} */
        UserRole: "admin" | "editor" | "user";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    auth_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    logout_and_invalidate_sessions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Logged out successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
        };
    };
    refresh_access_token: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            /** @description Unauthorized - Invalid or expired refresh token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    create_editor: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateEditorRequest"];
            };
        };
        responses: {
            /** @description Editor created successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EditorResponse"];
                };
            };
            /** @description Unauthorized - Not an admin */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_editor_info: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EditorResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_all_halls: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HallPayload"][];
                };
            };
        };
    };
    update_hall: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HallPayload"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HallPayload"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    create_hall: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HallPostPayload"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HallPayload"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_one_hall: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Hall UUID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HallPayload"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    delete_hall: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Hall UUID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_all_locations: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LocationPayload"][];
                };
            };
        };
    };
    update_location: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LocationPayload"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LocationPayload"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    create_location: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LocationPostPayload"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LocationPayload"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_one_location: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Location UUID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LocationPayload"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    delete_location: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Location UUID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_all_productions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductionPayload"][];
                };
            };
        };
    };
    update_production: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProductionPayload"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductionPayload"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    create_production: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProductionPostPayload"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductionPayload"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_one_production: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Production UUID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductionPayload"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    delete_production: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Production UUID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_all_spaces: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpacePayload"][];
                };
            };
        };
    };
    update_space: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SpacePayload"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpacePayload"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    create_space: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SpacePostPayload"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpacePayload"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_one_space: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Space UUID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpacePayload"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    delete_space: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Space UUID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_build_version: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
        };
    };
}
