export type ProductionResponse = {
    id: string;
    source_id: number | null;
    slug: string;
    supertitle_nl: string | null;
    supertitle_en: string | null;
    title_nl: string | null;
    title_en: string | null;
    artist_nl: string | null;
    artist_en: string | null;
    meta_title_nl: string | null;
    meta_title_en: string | null;
    meta_description_nl: string | null;
    meta_description_en: string | null;
    tagline_nl: string | null;
    tagline_en: string | null;
    teaser_nl: string | null;
    teaser_en: string | null;
    description_nl: string | null;
    description_en: string | null;
    description_extra_nl: string | null;
    description_extra_en: string | null;
    description_2_nl: string | null;
    description_2_en: string | null;
    video_1: string | null;
    video_2: string | null;
    quote_nl: string | null;
    quote_en: string | null;
    quote_source_nl: string | null;
    quote_source_en: string | null;
    programme_nl: string | null;
    programme_en: string | null;
    info_nl: string | null;
    info_en: string | null;
    description_short_nl: string | null;
    description_short_en: string | null;
    eticket_info: string | null;
    uitdatabank_theme: string | null;
    uitdatabank_type: string | null;
};

export type ProductionCreateRequest = {
    source_id?: number | null;
    slug: string;
    supertitle_nl?: string | null;
    supertitle_en?: string | null;
    title_nl?: string | null;
    title_en?: string | null;
    artist_nl?: string | null;
    artist_en?: string | null;
    meta_title_nl?: string | null;
    meta_title_en?: string | null;
    meta_description_nl?: string | null;
    meta_description_en?: string | null;
    tagline_nl?: string | null;
    tagline_en?: string | null;
    teaser_nl?: string | null;
    teaser_en?: string | null;
    description_nl?: string | null;
    description_en?: string | null;
    description_extra_nl?: string | null;
    description_extra_en?: string | null;
    description_2_nl?: string | null;
    description_2_en?: string | null;
    video_1?: string | null;
    video_2?: string | null;
    quote_nl?: string | null;
    quote_en?: string | null;
    quote_source_nl?: string | null;
    quote_source_en?: string | null;
    programme_nl?: string | null;
    programme_en?: string | null;
    info_nl?: string | null;
    info_en?: string | null;
    description_short_nl?: string | null;
    description_short_en?: string | null;
    eticket_info?: string | null;
    uitdatabank_theme?: string | null;
    uitdatabank_type?: string | null;
};

export type ProductionUpdateRequest = ProductionCreateRequest & {
    id: string;
};
