services:
  frontend:
    build:
      context: ../../frontend
      args:
        - NEXT_PUBLIC_SITE_URL=${NEXT_PUBLIC_SITE_URL}
        - NEXT_PUBLIC_API_URL=http://api:80/api
        - PREVIEW_NAME=${PREVIEW_NAME}
    container_name: ${COMPOSE_PROJECT_NAME}_frontend
    environment:
      NEXT_PUBLIC_SITE_URL: ${NEXT_PUBLIC_SITE_URL}
      NEXT_PUBLIC_API_URL: http://api:80/api
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${PREVIEW_NAME}.rule=PathPrefix(`/${PREVIEW_NAME}`)"
      - "traefik.http.routers.${PREVIEW_NAME}.entrypoints=websecure"
      #- "traefik.http.middlewares.${PREVIEW_NAME}-strip.stripprefix.prefixes=/${PREVIEW_NAME}"
      #- "traefik.http.routers.${PREVIEW_NAME}.middlewares=${PREVIEW_NAME}-strip"
      - "traefik.http.services.${PREVIEW_NAME}.loadbalancer.server.port=3000"
      - "traefik.http.routers.${PREVIEW_NAME}.tls.certresolver=letsencrypt"
    networks:
      - traefik
      - internal

  api:
    build:
      context: ../../backend
    container_name: ${COMPOSE_PROJECT_NAME}_api
    environment:
      DATABASE_URL: postgres://${PREVIEW_DB_USER}:${PREVIEW_DB_PASSWORD}@${COMPOSE_PROJECT_NAME}_db:5432/${PREVIEW_DB_NAME}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${PREVIEW_NAME}-api.rule=PathPrefix(`/${PREVIEW_NAME}/api`)"
      - "traefik.http.middlewares.${PREVIEW_NAME}-api-strip.stripprefix.prefixes=/${PREVIEW_NAME}/api"
      - "traefik.http.routers.${PREVIEW_NAME}-api.middlewares=${PREVIEW_NAME}-api-strip"
      - "traefik.http.routers.${PREVIEW_NAME}-api.entrypoints=websecure"
      - "traefik.http.services.${PREVIEW_NAME}-api.loadbalancer.server.port=3001"
      - "traefik.http.routers.${PREVIEW_NAME}-api.tls.certresolver=letsencrypt"
    networks:
      - traefik
      - internal

  db:
    image: postgres:18
    container_name: ${COMPOSE_PROJECT_NAME}_db
    environment:
      POSTGRES_USER: ${PREVIEW_DB_USER}
      POSTGRES_PASSWORD: ${PREVIEW_DB_PASSWORD}
      POSTGRES_DB: ${PREVIEW_DB_NAME}
    volumes:
      - db_data:/var/lib/postgresql
    networks:
      - internal

volumes:
  db_data:

networks:
  traefik:
    external: true
  internal:
    driver: bridge
