[package]
name = "db"
version = "0.1.0"
edition = "2024"
publish = false

[lib]
name = "db"
path = "src/lib.rs"

[lints]
workspace = true

[dependencies]
tracing = { workspace = true }
serde = { workspace = true }
uuid = { workspace = true, features = ["serde"] }
chrono = { workspace = true, features = ["serde"] }
thiserror = { workspace = true }

sqlx = { workspace = true, features = [
    "migrate",
    "macros",
    "json",
    "chrono",
    "uuid",
] }
ormlite = { version = "0.24.3", features = ["default-postgres"] }
utoipa = { version = "5.4.0", features = ["uuid", "chrono"] }
serde_json = "1.0"

[dev-dependencies]
sqlx = { workspace = true, features = [
    "migrate",
    "macros",
    "json",
    "chrono",
    "uuid",
] }
tokio = { workspace = true, features = ["rt-multi-thread", "macros"] }
uuid = { workspace = true, features = ["serde"] }
