name: Discord Notification

on:
  push:
  pull_request:
  issues:
  issue_comment:
  commit_comment:
  discussion:
  discussion_comment:

jobs:
  discord:
    runs-on: ubuntu-latest
    steps:
      - name: Send to Discord
        env:
          WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          payload="{\"content\":\"Repo update by $GITHUB_ACTOR: $GITHUB_EVENT_NAME\"}"
          curl -H "Content-Type: application/json" -X POST -d "$payload" $WEBHOOK_URL
