name: Frontend tests

on:
  workflow_call:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  test:
    if: github.event.pull_request.draft == false
    runs-on: kaya-sem-house
    container:
      image: mcr.microsoft.com/playwright:v1.59.1-jammy
      options: -v /cache/npm:/github/home/.npm -v /cache/playwright:/root/.cache/ms-playwright
    steps:
      - name: Clean up workspace
        run: |
          docker run --rm -v ${{ github.workspace }}:/workspace alpine sh -c "chown -R $(id -u):$(id -g) /workspace"
        continue-on-error: true

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: |
          cd frontend
          npm ci

      - name: Install Playwright browsers
        run: cd frontend && npx playwright install --with-deps chromium

      - name: Run Typecheck
        run: |
          cd frontend
          npm run typecheck

      - name: Run unit/integration tests and generate coverage
        run: |
          cd frontend
          npm run test:coverage -- --reporter=default --reporter=junit --outputFile=junit.xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          files: frontend/coverage/lcov.info
          flags: frontend
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true

      - name: Upload test results to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: frontend
          files: frontend/junit.xml
          report_type: test_results

      - name: Run Playwright E2E tests
        run: npm run test:e2e
        working-directory: frontend
        env:
          NEXT_PUBLIC_SITE_URL: "http://localhost:3000"
          NEXT_PUBLIC_API_URL: "http://localhost:3001/api"
          NEXT_PUBLIC_MEDIA_URL: "http://dev-bucket.s3.garage.localhost:3902"

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: frontend/playwright-report/
          retention-days: 30

      - name: Clean up workspace
        run: |
          docker run --rm -v ${{ github.workspace }}:/workspace alpine sh -c "chown -R $(id -u):$(id -g) /workspace"
        continue-on-error: true
